### ISSUE TITLE
Unable to login to GitHub

### ISSUE THREAD

**Issue by im-coder-lg** [andrewbrey/flot#1]
Thanks a lot for this project. This is really good, and I can now view multiple webpages at once. I have some problems. I use Windows 7 Build 7601, and I installed Flot. I wanted to try using GitHub while I am logged in but I couldn't log in. The webpage loads successfully, but when I put the username and password, it just reloads the page and doesn't log me in. How can I fix this?

**Comment by andrewbrey** [comment]
Hi @im-coder-lg thanks for using Flōt! As it says in the README, several web security features are disabled in the chromium browser being used by electron, and I _suspect_ that this is the reason that the GitHub session is not being saved when you try to log in.

Something like the following - after entering your username an password GitHub tries to set an `https only` cookie; it can't successfully do that because web security features have been disabled, and so when the site redirects you to "your home page" after signing in, no authentication cookie is present and so it kicks you back out to the unauthenticated section of the site.

Ultimately, within Flōt I discourage the use of any website that requires sign in because you can't trust the websites with your credentials or any entered information when security features are disabled. Flōt is meant as a toy, targeting "read only" viewing of publicly accessible websites, and any issues encountered beyond that scope are discouraged.

I'm going to mark your issue as "won't fix" because this is not a use case that Flōt is designed for, but thank you for trying the app and for participating in the repository!

**Comment by im-coder-lg** [comment]
Anytime! Flōt isn't a fully-fledged browser, so I will have to get habituated with it but this is a really cool project. :+1:
